[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
public-ip = "0.2.2"
global_lib = {"path" = "../global_lib/"}
bincode = "1.3.3"
tokio = { version = "1.37.0", features = ["full"] }    
sysinfo = "0.33.1"
local-ip-address = "0.6"
    